### ISSUE TITLE
NaNs produced with LRT.LD.plating

### ISSUE THREAD

**Issue by krystianll** [eeeeeric/rSalvador#10]
Dear Mr. Zheng,
I have written a script that allows to make pairwise comparisons of mutation rates (each to each) and that's when I discovered some problems with calculations using likelihood ratio test. Here are some data from the fluctuation assay:
```R
Strain1 <- c(24, 7, 6, 9, 8, 24, 25, 24, 33, 24, 29, 23, 16, 53, 21, 8, 42, 10, 37, 60, 25, 20, 73)
Nt1 <- 5.45e+09
e1 <- 0.05
Strain2 <- c(478, 92, 97, 254, 390, 141, 639, 439, 233, 409, 639, 313, 405, 310, 317, 350, 473, 343, 291, 82, 361, 457, 350, 317, 350, 361, 353, 285, 350, 332, 428, 387, 169, 237, 328, 478, 365, 296, 364, 364, 409, 849, 1337, 306)
Nt2 <- 4.79e+09
e2 <- 0.005
```
Let's pretend for now that the plating efficiency was 1:
```R
LRT.LD(Strain1, Strain2, R=Nt2/Nt1)
```
which produces:
```
[1] NaN NaN
Warning messages:
1: In log(p[data + 1]) : NaNs produced
2: In log(p[data + 1]) : NaNs produced
```
This doesn't break the program and the only outcome is NaN in the output matrix. I suppose it's not too bad since this means that P is close to 0 (however, the algorithm sometimes actually produces 0, as I will show later).
Now lets incorporate the plating efficiency info:
```R
LRT.LD.plating(Strain1, Strain2, R=Nt2/Nt1, e1=e1, e2=e2)
```
which gives:
```
Error in seq.convolute(eta, p) : 
  NA/NaN/Inf in foreign function call (arg 3)
```
and this breaks the program.
As I suppose, this is somehow connected to the huge difference between mutation rates of both strains. However, let's compare Strain 2 with Strain 3, which is actually a weaker mutator than Strain 1, so the difference between Strain 2 and Strain 3 is even bigger:
```R
Strain3 <- c(4, 1, 0, 1, 4, 1, 4, 1, 0, 2, 5, 8, 1, 1, 1, 8, 0, 2, 3, 0, 1, 0, 0, 3)
Nt3 <- 4.09e+09
e3 <- 0.05
```
In this case `LRT.LD.plating` also renders error in `seq.convolute` but `LD.plating` does not and renders 0:
```
> LRT.LD(Strain2, Strain3, R=Nt3/Nt2)
[1] 338.1852   0.0000
```

Unfortunately, this problem is way beyond my understanding of statistics and I have no idea if it's possible to patch?

**Comment by krystianll** [comment]
Sorry! I think I know where the problem comes from. In both `combo.LD` and `combo.LD.plating`, an initial guess for Mc is calculated using Jones method of the median. However, in a situation like above, where we have ~20 very low counts and ~40 extremely high counts, the median-method-calculated m will be close to those ~40, whereas MLE-calculated m will obviously be much closer to those ~20. As a consequence, the `combo.LD` produces a negative value of m.

I changed this:
```R
{if (median(Xc)==0) m0=p0.plating(Xc,ec) else m0=jones.median.plating(Xc,ec) } #option A
```
to this:
```R
{if (median(Xc)==0) {m0=p0.plating(Xc,ec)}
    else {
      if (median(X1) < median(X2)) { m0=jones.median.plating(X1,e1) }
      else { m0=jones.median.plating(X2,e2) }
    }
  } #option A
```

It appears to work. No NaNs in my matrix.

**Comment by isabelmcr1** [comment]
Dear Mr. Zheng, 
I also got the NaNs issue when using the LRT.LD.plating function with the following data: 
> AmkR_1 <- c(25, 11, 67, 10, 15, 14, 9, 12)
> AmkR_2 <- c(90, 175, 130, 95, 136, 125, 120, 45, 55)
> rsalvador::LRT.LD.plating(AmkR_1, AmkR_2, e1=0.1, e2=0.02)
[1] NaN NaN
Warning messages:
1: In log(p[data + 1]) :  NaNs produced
2: In log(p[data + 1]) :  NaNs produced

It seems that if I change e1 to be 0.02 and e2 to be 0.1 it works, but making that change would be incorrect in my view, since e1=0.1 was the plating efficiency for AmkR_1 and e2=0.02 was the plating efficiency for AmkR_2. 
I am sorry, but I did not understand the explanation given by krystianll in the previous comment. Could you help me solve this issue?
Thanks a lot!

**Comment by eeeeeric** [comment]
> The function LRT.LD.plating requires the value of R, which is Nt of the second
> experiment divided by Nt of the first experiment. Therefore, I assume Nt=2.5e7
> for the first experiment, and Nt=5.0e7 for the second experiment. That is,
> I assume R=2.0.  You case also requires an initial value for init.mc, which
> is rare. So you can proceed as follows.
> 
> ```
> > x=c(25, 11, 67, 10, 15, 14, 9, 12)
> > y=c(90, 175, 130, 95, 136, 125, 120, 45, 55)
> > LRT.LD.plating(x,y,2,0.1,0.02)
> Convergence fails. A new starting value may work.
> Convergence fails. A new value of init.mc may help.
> [1] NA
> > LRT.LD.plating(x,y,2,0.1,0.02,init.mc=2.3)
> [1] 5.574004e+01 8.271162e-14
> > LRT.LD.plating(x,y,2,0.1,0.02,init.mc=12.3)
> [1] 5.574004e+01 8.271162e-14
> ```
> 
> In addition, you can use webSalvador, as shown in the attached screenshot. webSalvador is accessible at
> 
> https://websalvador.eeeeeric.com/
> 
> ![websalvador](https://user-images.githubusercontent.com/3723705/104525103-19850b80-55c5-11eb-8fea-9dee703d6cbe.png)
> 
> Best regards,
> Qi Zheng
@qzheng491
