### ISSUE TITLE
Installing rSalvador on a Mac

### ISSUE THREAD

**Issue by flora87** [eeeeeric/rSalvador#2]
Hello, I've been trying to install rSalvador on a Mac and I've been having some issues.
This is the last I've done:

1. copy the file rsalvador_1.5.tgz to a convenient directory.
2. In R, change to the directory where rsalvador_1.5.tgz is residing
3. Execute install.packages('rsalvador_1.5.tgz')

But I get a warning saying that the package is not available for my r version (3.1.2)
I already tried to install rSalvador for the latest version, and I keep on having the same issue:

  package ‘rsalvador_1.5.tgz’ is not available (for R version 3.3.1)

Could you please help me?

**Comment by eeeeeric** [comment]
Hi flora, can you run `R CMD INSTALL rsalvador_1.5.tgz` from the command line? Does that work for you?

**Comment by flora87** [comment]
I ran the command from the terminal, and it seems like installation is done:

* installing to library ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library’
* installing *binary* package ‘rsalvador’ ...
* DONE (rsalvador)

However, when I call the package in r, I get the following error:

library(rsalvador)

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rsalvador/libs/rsalvador.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rsalvador/libs/rsalvador.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.2/Resources/lib/libR.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rsalvador/libs/rsalvador.so
  Reason: image not found
Error: package or namespace load failed for ‘rsalvador’

Please note that I looked for the file rsalvador.so in the mentioned directory, just to make sure that the file is there. It is. So I don't know exactly how to fix the error.

**Comment by eeeeeric** [comment]
Hmm, I'm noticing versions 3.3 and 3.2 in your error message. Do you have both versions installed? That may be the cause. Perhaps try uninstalling one of them, and reinstalling rSalvador after doing so.

**Comment by flora87** [comment]
I deleted the r app (just by dragging it to the trash icon)
then, from the console in rstudio, I called the package 

library(rsalvador)

And it worked!

Thanks Eric!

**Comment by eeeeeric** [comment]
Happy to help, glad we could resolve this! :)

**Comment by eeeeeric** [comment]
Happy to help, glad we could resolve this! :)
