### ISSUE TITLE
rSalvador encountered computational hurdles

### ISSUE THREAD

**Issue by mitchso** [eeeeeric/rSalvador#22]
Hello!

First off thank you for creating such a useful tool for the study of mutation rates. It has been very helpful!

I am using the websalvador tool and have come across an error that I am not sure how to fix while trying to compare 2 mutation rates using "Lea-Coulson Model (ε < 1): comparison of rates". It says:

"
rSalvador encountered computational hurdles. You may check raw data (they must
be either zeros or positive integers), change initial values, or increase
sample size (i.e., number of sister cultures).
"

Since I dont know what about the data is causing trouble, I am not sure how to fix this. Can you please advise? I will post a screenshot with the data I have entered.
<img width="1116" alt="Screen Shot 2021-05-11 at 2 32 38 PM" src="https://user-images.githubusercontent.com/30331279/117866969-bef37780-b265-11eb-8a5f-3824b9243068.png">

**Comment by mitchso** [comment]
Thank you for the quick reply Dr. Zheng!

I am now able to get results, however I have a follow-up question. For my experiment I plated the entire volume of each culture, so the plating efficiency is 1. Is there a reason why E=1 is not allowed for comparison of rates? I am instead using 0.99 to work through websalvador. If there is an issue with E=1, is using 0.99 going to lead to incorrect results?

Thank you!
Mitch

**Comment by mitchso** [comment]
I have also just encountered another issue when trying to compare rates with a hypermutator. Is there something that can be done to resolve this?

<img width="1095" alt="Screen Shot 2021-05-12 at 9 41 03 AM" src="https://user-images.githubusercontent.com/30331279/117984925-4264a580-b306-11eb-873b-322ce9003fcb.png">

**Comment by eeeeeric** [comment]
> Hi, Mitch,
>  
> When plating is complete, we should use a different method (page). Setting e=0.99 is not recommended. Please see the two attached images.
> 
> Best wishes,
> 
> Qi Zheng

![reply_may_12](https://user-images.githubusercontent.com/3723705/118016621-3c2cf400-b31b-11eb-8c15-4c20ace7c74a.png)
![reply_may_12A](https://user-images.githubusercontent.com/3723705/118016623-3cc58a80-b31b-11eb-887f-03a7741d744a.png)
