### ISSUE TITLE
Install from github

### ISSUE THREAD

**Issue by pbiecek** [eeeeeric/rSalvador#3]
The easiest way to install your package is to run
```
devtools::install_github("eeeeeric/rSalvador", subdir = "rsalvador")
```
Way easier than instructions from http://eeeeeric.com/rSalvador/ ;-)

**Comment by eeeeeric** [comment]
That is very cool, thanks for the info! I should update the website with this.

**Comment by YiweiZhu** [comment]
Hi, @eeeeeric , I tried this command, but failed again. I find the downloaded file is tar file, but my computer system is Windows. I infer this may be the reason of installation failure. 
> devtools::install_github("eeeeeric/rSalvador",subdir = "rsalvador")
Downloading GitHub repo eeeeeric/rSalvador@master
√  checking for file 'C:\Users\30789\AppData\Local\Temp\RtmpEdVgph\remotes26f43f1d3071\eeeeeric-rSalvador-3c99df9\rsalvador/DESCRIPTION' ...
-  preparing 'rsalvador':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'rsalvador_1.7.tar.gz'
   
* installing *source* package 'rsalvador' ...
** using staged installation
** libs

*** arch - i386
Error: Failed to install 'rsalvador' from GitHub:
  (converted from warning) installation of package ‘C:/Users/30789/AppData/Local/Temp/RtmpEdVgph/file26f4187d4f50/rsalvador_1.7.tar.gz’ had non-zero exit status

**Comment by YiweiZhu** [comment]
I find it is because I didn't add Rtools to system path. I fix it now and install the package successfully. :D
