### ISSUE TITLE
What is the assumption of N(t)? How to feed in my N(t)?

### ISSUE THREAD

**Issue by aapsonn** [eeeeeric/rSalvador#4]
Hi, i do not quite understand why none of the methods requires N(t) values? You can give CV of your N(t), but not the actuall estimates of N(t)? Is it a hard-coded value? 
I am sorry if it a such a dumb question.

Thank you

**Comment by eeeeeric** [comment]
Measuring N(t) for all cultures is impracticable. In practice, only a few (usually about 3) cultures are sampled to determine an average N(t). Most rSalvador functions require just the mutant counts and return to the user an estimate of the parameter m -- the expected number of mutations per culture. An estimate of the mutation rate is  computed as follows:

estimated mutation rate = (estimated m) / (average N(t))

According to a 2016 study (Q Zheng, A second look at the final number of cells in a fluctuation experiment, Journal of Theoretical Biology 401 (2016) 54-63), variation in N(t) is usually so small in practice that it is  unnecessary to measure N(t) for all cultures. This is an encouraging finding, as the task of measuring N(t) for all cultures is too laborious to be practical. For further information about rSalvador, please consult Zheng's G3 paper titled "rSalvador: An R package for the fluctuation experiment", freely available at

http://www.g3journal.org/content/early/2017/10/30/g3.117.300120
