### ISSUE TITLE
Error with mutation rate calculation using newton.LD.plating function

### ISSUE THREAD

**Issue by isabelmcr1** [eeeeeric/rSalvador#6]
Hi! 
I keep having this error come up and I can't understand why it's happening, I'm new to this tool. 
This is what I have been trying to calculate: 
```
> nuc_pMV361_resistentes <- c(4420, 2680, 3400, 8000, 3280, 4060, 2460, 4700)
> rsalvador::newton.LD.plating(nuc_pMV361_resistentes, 0.05)
Error in if (abs(m1 - m0)/m0 < tol) { : 
  missing value where TRUE/FALSE needed
```
It has also happened with other cuantities of data, I don't seem to be able to get around this issue. I would appreciate some help! 
Thanks,

**Comment by eeeeeric** [comment]
Posting on behalf of Qi Zheng:

> Hi, rSalvador user,
> 
> This is an initial diagnosis. In the past, some users attempted to infer the number of mutants in a tube by dividing the number of mutants found in the plated portion by the plating efficiency. This is incorrect. 
> 
> In the data you cited, all mutant counts are divisible by 20. Hence, I suspect that your mutant counts may have been unnecessarily inflated in a similar way. If we divide those mutant counts by 20, we may recover the original mutant counts. The analysis would then proceed as follows.
> 
> 
> > z=nuc_pMV361_resistentes
> > z
> [1] 4420 2680 3400 8000 3280 4060 2460 4700
> > y=z*0.05
> > y
> [1] 221 134 170 400 164 203 123 235
> > newton.LD.plating(y,e=0.05)
> [1] 506.7903
> 
> 
> If my assumption was wrong, please send me an email.
> 
> Best regards,
> Qi Zheng
