### ISSUE TITLE
Use rSalvador to calculate mutation rate in original culture

### ISSUE THREAD

**Issue by aishasyeda** [eeeeeric/rSalvador#7]
Hi,

I have a very high proportion of mutants in my culture and it is not possible to count all colonies if I plate the entire culture. Also I don't priori know how many mutants I will recover in each experiment. So I took 5 ul of the 100 ul culture that I grew for each experiment, made 10 fold dilution series and spotted 5 ul from each dilution on selection plates. I then counted the individual colonies from dilutions where they were countable and noted the dilution and the number of colonies I observed. Which is the best way to calculate mutation frequencies for these?

I tried calculating the number of mutants in 5 ul of original culture as r = no of colonies * 20 * dilution factor. Then I used newton.LD.plating(y, e=0.05). I got the values for most experiments but for those where the values of r were very high (>1000) I got an error. Your help to calculate these will be appreciated. Many thanks.

**Comment by eeeeeric** [comment]
Commenting on behalf of Qi Zheng:

> Hi, rSalvador user,
> 
> As I recently explained to another user, the method of using a formula like "r=no of colonies * 20" is incorrect.  But this experiment is more complicated.
> 
> In this experiment, you first took a portion of 5 ul out of each 100 ul culture. If the mutant counts were manageable, you should proceed by following my reply to the user I just mentioned. But in your case, there were still too many mutants for you to count. As a remedy, you essentially plated only a small portion from each of the 5 ul subcultures. This practice violated current protocols and no existing algorithms are applicable. 
> 
> In retrospect, you might first use a few "pilot" cultures to determine an appropriate plating efficiency. With the information now available to me, you might just plate a 1.0 ul portion out of each original 100 ul culture.
> 
> In future correspondence, please attach actual data to help me make a more useful diagnosis. 
> 
> Best regards,
> Qi Zheng

**Comment by aishasyeda** [comment]
Hi Qi Zheng,

Many thanks for your reply. Please find sample dataset attached. I was wondering if getting all culture counts to the same common dilution is a way forward with the existing data?

[sample dataset.xlsx](https://github.com/eeeeeric/rSalvador/files/3335266/sample.dataset.xlsx)

**Comment by eeeeeric** [comment]
> Hello, rSalvador user,
> 
> 
> Yes, you were right: there should be only one common plating efficiency for all cultures within the same experiment. Therefore, the attached data cannot be analyzed.
> 
> Please keep this in mind: the input data should always be the numbers of mutants we actually observed. In other words, we should never try to infer the number of mutants in the original culture by multiplying the observed number of mutants by the dilution factor. Consider the following example.
> 
> The experimenter took a 0.05 ul culture from each of ten 10 ul cultures. The observed numbers of mutants were:
> 
>  6   5  10   8  24  13 165  15   6  10 
> 
> and our input data should be
> 
> > mydata=c(6,5,10,8,24,13,165,15,6,10)
> 
> and the expected number of mutations per (original) culture can be estimated by executing 
> 
> > newton.LD.plating(mydata,e=0.005)
> [1] 281.2458
> 
> We should never try to "recover" the numbers of mutants in the original cultures by executing
> 
> > mydata*200
>  [1]  1200  1000  2000  1600  4800  2600 33000  3000  1200  2000
> 
> This clearly is incorrect. For further information about this technical point, please refer to the G3 paper  in the December 2017 issue. Figure 2 in that paper explains vividly why we should not try to recover the original mutant counts by multiplication.
> 
> Finally, I do not know the precise definitions of the two types of dilution factors in your data file.
> 
> Best regards,
> Qi Zheng
>

**Comment by aishasyeda** [comment]
Many thanks again. There are two sets of data in my file - one is the mutant count with the respective dilution factors (columns 1 and 2) and the other is the total count with the corresponding dilution factors (columns 3 and 4.
Best regards,
Aisha

**Comment by eeeeeric** [comment]
> Hi rSalvador user,
> 
> As I pointed out before, we must have a common plating efficiency within an experiment. For the sake of  illustration, I consider observations 1, 7, 9, and 10. The common plating efficiency is 0.01. Therefore,
> 
> > small.data=c(16,66,52,4)
> > small.data
> [1] 16 66 52  4
> > newton.LD.plating(small.data,e=0.01)
> [1] 184.504
> 
> Thus, the estimated number of mutations per culture is 184.50.
> 
> Now, you may use data in columns 3 and 4 to obtain an estimate of Nt. And the desired mutation rate will follow.
> 
> Best regards,
> Qi Zheng
