### ISSUE TITLE
Error with plating efficiency using newton.LD.plating 

### ISSUE THREAD

**Issue by vanessabaldin** [eeeeeric/rSalvador#8]
Hi, I’m using rSalvador to calculate mutation rates and I keep having an error using the newton.LD.plating function. 
I am calculating the plating efficiency dividing plated volume by total culture volume. I am plating 1 mL from a total culture of 1.5 mL so my plating efficiency is 0.6667. Using my data and this plating efficiency this error keeps coming up: 

```
**> mc_mutT_1946
[1] 10  8  3 10  6  0  9  9
> rsalvador::newton.LD.plating(mc_mutT_1946, 0.6666666667)
Error in hypergeo(1, 2, n + 2, 1 - e) : 
  could not find function "hypergeo"**
```

I don’t understand why this is happening and would appreciate some help. Thanks in advance. 
Vanessa

**Comment by eeeeeric** [comment]
> Hi rSalvador user,
> 
> As the Beginner's Guide (p.1) says, you need to install the R package "hypergeo" by executing
> 
> install.packages('hypergeo')
> 
> You only need to install it once. Now, the rest is straightforward:
> 
> > mydata=c(10, 8, 3, 10, 6, 0, 9, 9)
> > mydata
> [1] 10  8  3 10  6  0  9  9
> > newton.LD.plating(mydata,e=0.6667)
> [1] 3.791294
> 
> Best regards,
> Qi Zheng
